name: CI

on:
  push:
    branches:
      - main

jobs:
  auto_sync:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: "My dummy test"
        run: |
          export PYOPENCL_TEST="portable:pthread"
          conda install pocl
          $CONDA/bin/pip install pyopencl
          $CONDA/bin/python3 main.py
