name: CI

on:
  push:
    branches:
      - main

jobs:
  auto_sync:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: "My dummy test"
        run: |
          conda create --name myenv
          conda activate myenv
          conda install -c conda-forge pocl
          export PYOPENCL_TEST="portable:pthread"
          pip install pyopencl
          python main.py
