name: CI

on:
  push:
    branches:
      - main

jobs:
  auto_sync:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "My dummy test"
        run: |
          curl -L -O -k https://tiker.net/ci-support-v0
          . ./ci-support-v0

          print_status_message
          clean_up_repo_and_working_env
          install_miniforge

          CONDA_ENVIRONMENT=.test-conda-env-py3.yml

          PATH="$MINIFORGE_INSTALL_DIR/bin/:$PATH" with_echo conda update conda --yes --quiet
          PATH="$MINIFORGE_INSTALL_DIR/bin/:$PATH" with_echo conda update --all --yes --quiet
          PATH="$MINIFORGE_INSTALL_DIR/bin:$PATH" with_echo conda env create --file "$CONDA_ENVIRONMENT" --name testing --quiet

          source "$MINIFORGE_INSTALL_DIR/bin/activate" testing

          # https://github.com/pypa/pip/issues/5345#issuecomment-386443351
          export XDG_CACHE_HOME=$HOME/.cache/$CI_RUNNER_ID

          with_echo conda install --quiet --yes pip
          with_echo conda list

          with_echo chmod a+x main.sh
          with_echo ./main.sh
